### ISSUE TITLE
problem with migrate

### ISSUE THREAD

**Issue by webpioneer** [chrisspen/django-chroniker#35] opened 2015-04-07 15:13 UTC
After a fresh install of django-chroniker using pip install django-chroniker, and adding it to INSTALLED_APPS. when i run python manage.py migrate, i get the following error:

@transaction.commit_manually
AttributeError: 'module' object has no attribute 'commit_manually'

pip install will automatically install django 1.8.

What version of Django would you recommend installing django-chroniker with ?

**Comment by chrisspen** [comment] 2015-04-23 20:57
This is a duplicate of #34. This should now be fixed in version 0.8.0.

**Closed by chrisspen** 2015-04-23 20:57 UTC
