### ISSUE TITLE
Admin interface links are escaped

### ISSUE THREAD

**Issue by MA-Heshmatkhah** [chrisspen/django-chroniker#157] opened 2019-08-13 15:56 UTC
Links and custom buttons of the admin app are converted to safe text in Django 2.2.4:

![image](https://user-images.githubusercontent.com/10222466/62956392-1d2cc580-be08-11e9-8de0-d1832add210f.png)

**Comment by chrisspen** [comment] 2019-08-13 18:57
I've pushed fixes for this in the new release on PyPI.

**Comment by mordechaiyosef** [comment] 2019-08-29 09:46
Duplicate of #156 i fixed in pull request #159

**Closed** 2019-09-06 21:37 UTC
